### ISSUE TITLE
At TVHeadend Client on iPad "TVHeadend returned malformed JSON.. "

### ISSUE THREAD

**Issue by Sethach** [zipleen/tvheadend-iphone-client#147]
When I connect to my tvheadend server 3.9.2342 I get the message:
"Tvheadend returned malformed JSON - check your tvheadend character set for each mux and choose the correct one"

I did try UTF8 at each mux, no change. Then I tried AUTO - no change.
In addition I set up ISO-8859-1 for Germany - no change.

On the TV (client with FireTV and Kodi 14) I have EPG, but missing all German Umlaute.

The iPad does not show any program information or EPG.
What can I do to fix this?

**Comment by zipleen** [comment]
I specifically added that error message to know that the "error" was from processing the JSON response.
I've tried to cleanup the json, but it's not 100% full proof - the cleanup was just to help display something, even if it removed the extended characters. 

You need to check the web interface and see if it displays the EPG correctly - if it does, then contact me via email and give me access to your tvheadend or a dump of your EPG JSON call so I can test it locally.

The character set is the option that you need to set correctly for all your muxes - this should fix your issue, you just need to find the correct one.

**Comment by Sethach** [comment]
Hi Luis,

 

thank you for your response!

 

First of all some background information on my installation:

-          Debian v7.6

-          Tvheadend 3.9.2342~g022e8d4

-          FireTV with Kodi 14.0

-          Windows 7 PX with IE 11

-          iPad iOS 7 safari

 

FireTV:

EPG is working, but all German Umlaute are missing, there is no spare character, they are simply gone.

 

Windows 7 IE

EPG is working, but the German Umlaute are replaced by sqare blocks

 

iPad:

EPG is working, but the German Umlaute are replaced by sqare blocks

 

Tvheadend client on the ipad:

No EPG, but the message:

Tvheadend returned malformed JSON -  check you theadend’s  charakter set  for each mux and choose the correct one.

 

 

The setting on the tvheadend character is as follows:

-          configuration – DVBinputs – Networks Advanced settings Character Set: UTF-8

-          configuration – DVBinputs – Muxes each enabled mux: Edit Mux Advanced settings Character set: UTF-8

 

Before Tvheadend 3.9.2342 I have had 3.9.2316, and the Umlaute have been ok. I am not sure if this has something to do with the tvheadend version, or with the fact that I

Have made clean new installation of my debian. Somehow it seems weird.

 

I have tried the character set 

O AUTO

O ISO-8859-1

with no effect. But I am unaware what I have to do to make the change working.

Do I have to delete some kind of EPG cache somewhere in the system?

 

If I look into the /home/hts/.hts/tvheadend/epgdp.v2 I can find German Umlaute – but I have no idea what this file is used for.

 

I think it is an tvheadend server issue, so I will post this also in tvheadend forum.

 

 

Regards

ralf

Von: Luis Fernandes [mailto:notifications@github.com] 
Gesendet: Samstag, 10. Januar 2015 03:23
An: zipleen/tvheadend-iphone-client
Cc: Sethach
Betreff: Re: [tvheadend-iphone-client] At TVHeadend Client on iPad "TVHeadend returned malformed JSON.. " (#147)

 

I specifically added that error message to know that the "error" was from processing the JSON response.
I've tried to cleanup the json, but it's not 100% full proof - the cleanup was just to help display something, even if it removed the extended characters. 

You need to check the web interface and see if it displays the EPG correctly - if it does, then contact me via email and give me access to your tvheadend or a dump of your EPG JSON call so I can test it locally.

The character set is the option that you need to set correctly for all your muxes - this should fix your issue, you just need to find the correct one.

**Comment by Sethach** [comment]
Hello Luis,

 

thank you for your reply.

 

First of all I would like to give you an information about my setup:

O Media Server

-          Tvheadend 3.9.2342 running on Debian Linux 7.8 wheezy

-          2 Sundtek Sundtek DVB-S/S2 (IV) SAT Tuner

O Clients

-          2 FireTV with Kidi 14

-          iPad 3 (iOS 7) tvheadend App

-          iPad Air (iOS 7) tvheadend App

-          Windows 7 with IE 11

 

I made a clean installation of the Media Server (incl. OS), and before I have had tvheadend 3.9.2316 without any problems of missing Umlaute of JSON messages.

 

At tvheadend I setup the following:

A:

                Configuration – DVB Inputs – Networks (edit Network) Character Set: UTF-8

                Configuration – DVB Inputs – Muxes  (edit Mux) Character Set: UTF-8 (for each enabled mux)

Result on clients:

-          Fire TV shows EPG, but all umlaute are missing, brief info below the station name without umlaute

-          iPad 3 “Tvheadend returned malformed JSON..”, no EPG, no brief info below the station name

-          iPad Air “Tvheadend returned malformed JSON..”, no EPG, no brief info below the station name

-          Windows browser shows no EPG by default, only when entering a search criteria I get the info 
Umlaute replaced by small boxes

-          Safari iPad browser EPG ok, Umlaute missing

B:

                Configuration – DVB Inputs – Networks (edit Network) Character Set: AUTO

                Configuration – DVB Inputs – Muxes  (edit Mux) Character Set: AUTO (for each enabled mux)

Result on clients:

-          Fire TV shows EPG, but all umlaute are missing, brief info below the station name without umlaute

-          iPad 3 “Tvheadend returned malformed JSON..”, no EPG, no brief info below the station name

-          iPad Air “Tvheadend returned malformed JSON..”, no EPG, no brief info below the station name

-          Windows browser shows no EPG by default, only when entering a search criteria I get the info 
Umlaute replaced by small boxes

-          Safari iPad browser EPG ok, Umlaute missing

SAME AS A

C:

                Configuration – DVB Inputs – Networks (edit Network) Character Set: ISO-8859-1

                Configuration – DVB Inputs – Muxes  (edit Mux) Character Set: ISO-8859-1 (for each enabled mux)

Result on clients:

-          Fire TV shows EPG, umlaute ok, brief info text ok (correct umlaute)

-          iPad 3 “Tvheadend returned malformed JSON..”, EPG ok, brief info ok (correct umlaute)

-          iPad Air “Tvheadend returned malformed JSON..”, EPG ok, brief info below the station name, most missing (correct umlaute)

-          Windows browser shows no EPG by default, only when entering a search criteria I get the info 
Umlaute ok

-          Safari iPad browser EPG ok, Umlaute ok

 

So the questions are:

why are the two ipads different 

why do I still get the JSON message

why are the brief info below the station names most not shown?

 

Thank you very much

 

Ralf

P.S. I will post a similar description on the tvheadend forum to get help for the windows browser problem

 

 

Von: Luis Fernandes [mailto:notifications@github.com] 
Gesendet: Samstag, 10. Januar 2015 03:23
An: zipleen/tvheadend-iphone-client
Cc: Sethach
Betreff: Re: [tvheadend-iphone-client] At TVHeadend Client on iPad "TVHeadend returned malformed JSON.. " (#147)

 

I specifically added that error message to know that the "error" was from processing the JSON response.
I've tried to cleanup the json, but it's not 100% full proof - the cleanup was just to help display something, even if it removed the extended characters. 

You need to check the web interface and see if it displays the EPG correctly - if it does, then contact me via email and give me access to your tvheadend or a dump of your EPG JSON call so I can test it locally.

The character set is the option that you need to set correctly for all your muxes - this should fix your issue, you just need to find the correct one.

**Comment by zipleen** [comment]
Is this working now? From your forum post you said with ISO-8859-1 the characters now appear.
Regardless, this should be a encoding problem which is easier to fix in tvheadend. I'll close the ticket now.
