### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by abolhasanfathi** [zipleen/tvheadend-iphone-client#148]
Hi
I have a problem with compiling tvheadend-iphone-client. (https://github.com/zipleen/tvheadend-iphone-client)

I downloaded the Zip file then extracted it in my desktop.
ran pod install in terminal as you see:

![pod install](https://cloud.githubusercontent.com/assets/10627217/5890867/4045c9d0-a487-11e4-8a85-9794f3313882.png)

but when I tried to compile it, it gives me this error:
Lexical or Preprocessor Issue
 'TVHServerSettings.h' file not found
what should I do?

![search path](https://cloud.githubusercontent.com/assets/10627217/5890870/7e161e22-a487-11e4-8435-3e86302b9fa2.png)

(Search Paths for tvhClient under the Build Settings:
Framework Search Paths: 		$(inherited)
							$(SRCROOT)
							$(PROJECT_DIR)/tvheadend-ios-lib/vendor
							$(PROJECT_DIR)/vendor

Header Search Paths: 			$(inherited)
							$(SRCROOT)/tvheadend-ios-lib/tvheadend-ios-lib
							$(SRCROOT)/tvheadend-ios-lib/vendor

Library Search Paths: 			$(inherited)
							$(PROJECT_DIR)/tvheadend-ios-lib/vendor/libssh2-compiled
)

tank you

**Comment by zipleen** [comment]
Hi,

Downloading the zip file is not enough, you need to get the rest of the dependencies:
- tvheadend-ios-lib
- afnetworking 1.x
If you use git clone --recursive, it will take care of that for you.

My instructions in the homepage for getting the code ( https://github.com/zipleen/tvheadend-iphone-client#getting-the-code ) say:
Getting the code

git clone --recursive git://github.com/zipleen/tvheadend-iphone-client.git
pod install
Build and run ! Send your patches to me via a pull request ;)
