### ISSUE TITLE
Download channel icons via HTSP instead HTTP

### ISSUE THREAD

**Issue by janeczku** [zipleen/tvheadend-iphone-client#150]
HTSP v10+ API allows fetching the channel icon images via HTSP "fileopen". See https://tvheadend.org/projects/tvheadend/wiki/Htsp.

At the moment i have to open the 9981 port in my firewall just to get the icons. Would be nice to have all communications with tvheadend over a single tcp port.

**Comment by zipleen** [comment]
Hi,

HTSP is not used in tvhclient at all, all communication and control is done via the HTTP port.
If the channel images were to be downloaded over HTSP, you would still need the HTTP port open for everything else. All communications are done over a single tcp port - the http one.

See https://github.com/zipleen/tvheadend-iphone-client#technical-background-regarding-connection-to-tvheadend

Note: the only use for HTSP port in tvhclient is when you send a "play link" to XBMC.
