### ISSUE TITLE
Crash v. 2.7.2

### ISSUE THREAD

**Issue by nntndfrk** [zipleen/tvheadend-iphone-client#155]
Version 2.7.2 iOS 6.1.6 - crash on start-up

**Comment by zipleen** [comment]
Oh.. This is bad. I don't have any iOS 6 device to test this with and all beta testiers have iOS 8!
Xcode does not have any iOS 6 emulator as well..
If you can help me testing iOS6, send me an email at tvhclient at gmail and we'll talk over there

**Comment by one23** [comment]
Can confirm this.  Crash report says:  
```
Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
  Referenced from: /var/mobile/Applications/0176B2B7-58FF-4EEE-A0F0-086BFFEEFE3E/TvhClient.app/TvhClient
  Reason: image not found
  Dyld Version: 212.3.2
```
Perhaps a library not available in iOS 6?

**Comment by zipleen** [comment]
Hi @one23 ! Thanks for the crash report, much helpful because I don't have any iOS 6 device to test with.

By any chance can you help me test a build with that library set as optional? Can you send me an email at tvhclient at gmail if you can help me? 

Cheers

**Comment by one23** [comment]
Will do!
