### ISSUE TITLE
Latest stable 4.0.4 - Network error 401

### ISSUE THREAD

**Issue by dreamcat4** [zipleen/tvheadend-iphone-client#159]
Seems like it won't connect anymore, tvheadend v4.0.4.

**Comment by zipleen** [comment]
I have v4.1 installed and it works fine, scheduled the f1 recording 3 hours ago...
Can you provide some more logs? I won't be able to check any of it for 1 week though.

**Comment by dreamcat4** [comment]
Sure ok I can try to get that in a couple of days, `tvheadend.log` for:

* The latest stable release `v4.0.4`
* The `v4.1` (at this time, is ~160 commits behind master), to see if same thing happens (as yours is OK).

Please ask for any extra subsystems or trace you want. When different from the defaults.

**Comment by dreamcat4** [comment]
OK tvheadend `v4.0.4` stable:

```sh
$ docker exec -it tvh tvheadend --version
tvheadend: version 4.0.4
```

I tried 2 user accounts:

1) Account Limited as non-admin (regular user):

401 everything - [log](https://gist.github.com/dreamcat4/6863551e2b78cf5f9fd3)

2) Account which is admin (superuser):

401 everything - [log](https://gist.github.com/dreamcat4/f29074082c4671ca1f3c)

Sorry I didn't switch on and extra debugging or trace log. If that is needed to look further then you need to say [which ones](http://docs.tvheadend.org/Appendices/debugging/).


Next I will try `v4.1` git tag (same as you).

**Comment by zipleen** [comment]
There's one limitation that you must make sure you don't hit - after you "add server" it will default to 3.4, and then request the api version which will then be detected as the correct version. At this point I have code to reconnect again but this does not seem to work reliably - this means after you add a server or you change the server version (from 3.4 to 3.6 or to 4.0 or to whatever new api version happens to exist) you need to "select" the server at least twice to make sure the correct version is detected. You can see below the server list which version was detected and most importantly the version of the api being used internally.

In screenshots, you must make sure you see (A15) in the end of the "server":
![screen shot 2015-06-23 at 14 26 08](https://cloud.githubusercontent.com/assets/1225055/8306975/f0e5b38a-19b3-11e5-9586-2a25c09cdeb3.png)
There's only a handful of versions that are "detected":
- (32) -> 3.2...
- (34) -> 3.4, 3.5, 3.6 
- (A12) -> there was a point that 3.9 had a lot of broken api, I only support the latest "version 12" which means 3.9.XXX (less than 1000) probably don't work
- (A15) -> 4.0 and onwards

There could be new versions of the api, and if that's the case then I need to add support for them. But version 15 seems to be ok for 4.0 and 4.1, so make sure that the version is detected as (A15) and then check the logs.

This `HTTP/1.1 GET /api/serverinfo -- 401` is weird because it should return the api information, and you're seeing 401.

**Comment by dreamcat4** [comment]
Hello! OK thanks for this explanations :)

Sorry I'm being a bit slow. We should give more information: we are not on iPhone, it's an iPad.

Unfortunately it never show up that line with the connects / API version infos. At bottom of the settings screen it says:

```sh
TvhClient Version: 2.7.3 (661)
```

Perhaps I should delete / reinstall fresh again from App Store? We have automatic App Updates switched on... so kindda expected it to be upgraded automatically.

Perhaps we should also Wipe all of the App's Sandbox Data / Settings while we are at it? I will try those steps and report back afterwards.

**Comment by dreamcat4** [comment]
iPad Mini v1, iOS version: `8.3 (12F69)`

**Comment by zipleen** [comment]
That's the tvhclient version. I was referring to the tvheadend version that's detected .In ipad it's exactly in the same place, below "add new tvheadend" If you don't see it (which is normal right after adding a new server), close settings and open it again - it should be displayed.

![screen shot 2015-06-23 at 14 43 11](https://cloud.githubusercontent.com/assets/1225055/8307411/374d038a-19b6-11e5-9163-4bf5606d4b81.png)

**Comment by dreamcat4** [comment]
@zipleen OK I tried doing the following things:

* Remove app, including it's 'Documents and Data' from managed storgage settings menu
* Re-install app from app store - it shows the same version as previously (2.7.3 661)
* Start up my `v4.0.4` tvheadend server docker container
* Try again pressing the Server in the Settings list
* No API status line is ever shown.
* Switch to using `v4.1` tvheadend server with debugging mode (again it's a docker container)
* Same problem - No API version line shown, not connected, the tvheadend logs shows same `401`s.

You can see here (it's same thing)

https://gist.github.com/dreamcat4/f5f682c0d88c706f10cd

> This HTTP/1.1 GET /api/serverinfo -- 401 is weird because it should return the api information, and you're seeing 401. 

I agree this is strange, perhaps we can CURL and see. Unforunately the iPad we have is not jailbroken anymore, so we cannot CURL from the iPad device.

**Comment by zipleen** [comment]
well jailbreak was just released for 8.3 :D

anyway, you can try postman and see what happens. You can do a tcpdump (or wireshark) capture on port 9981 to see what's being sent and replicate it with postman (the chrome extension).

I still think there's something wrong with your setup, something is breaking the connection to tvheadend http port - you should check that with wireshark.

**Comment by dreamcat4** [comment]
@zipleen Here is my output from other computer on my local LAN:

```sh
$ curl 192.168.2.3:9981/api/serverinfo
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>401 Unauthorized</TITLE>
</HEAD><BODY>
<H1>401 Unauthorized</H1>
<P><A HREF="/">Default Login</A></P></BODY></HTML>
janitors-mac-mini ~/ id~$ 
```

So we might hazard guess that is something to do with it. Not sure yet what else to try. Still thinking about it.

**Comment by dreamcat4** [comment]
@zipleen & thanks for mentioning the jailbreak news. :)

**Comment by dreamcat4** [comment]
OK @zipleen from that access denied message it seemed to me as some local Access Control issue. Whereby the username / password was not always recognised or working reliably. I re-edit and re-saved the access control entry and now it connect ok. (version 4.0.4 server).

I guess maybe it's some weird bug in tvheadend (or it's web interfere) when I saved it, but then it revert back by itself afterward. I.e. when you refresh the page or come back later. It sound pretty unbelievable I know. Well never mind now.

Good news: Your App now show me in settings beneath the line:

```sh
Tvheadend Version: 4.0.4 (A15)
```

Which of course is where you told me to press several times the server entry.  (I try it again after re-saving the access control line). Thank you. Sorry to be a nuisance about it. Hopefully the access control setting does not revert again anymore. At least it is clear what to look for now.

BTW
I would appreciate if you can please confirm to me which one is the legitimate iOS 8.3 jailbreak? Since there can be many fake ones. Is it the TaiG one? [Y/N]

We can close the issue now.

**Comment by zipleen** [comment]
yup, https://twitter.com/taig_jailbreak/status/613297761409105920

Regarding the tvheadend server - didn't you try without any permissions? maybe that bug fix is actually the issue that you were encountering =)

I'll close the ticket then! Cheers.
