### ISSUE TITLE
Feature request: Build for tvOS

### ISSUE THREAD

**Issue by vicegold** [zipleen/tvheadend-iphone-client#162]
As the new tvOS for AppleTV is basically just iOS, would it be hard to "port" it to the AppleTV?

I would love to assist with a fitting design, if wanted :)

**Comment by zipleen** [comment]
I'm already decided that I'm porting it yesterday :p
Any design ideas are always appreciated!

**Comment by kenji21** [comment]
Just tried to add a tvOS app to the current project, some dependencies fails, removed them until it compile for the tv simulator (had to manually change supported platforms to tvOS on Pods.xcodeproj) :

```
#pod 'MobileVLCKit', '~> 2.2'
#pod 'WTStatusBar', '~> 0.0'
#pod 'GoogleAnalytics'
pod 'PDKeychainBindingsController', '~> 0.0'
#pod 'SDWebImage', '~> 3.7'
#pod 'SDSegmentedControl', :head
#pod 'UIActionSheet+Blocks', '~> 0.8'
#pod 'JASidePanels', '~> 1.3'
#pod 'MGSplitViewController', :git => 'git://github.com/zipleen/MGSplitViewController.git'
pod 'FontAwesomeIconFactory', '~> 1.4'
#pod 'NoticeView', '~> 3.0'
#pod 'CrashlyticsFrameworkIOS', '~> 3.0'
```

**Comment by zipleen** [comment]
I'm not going to add a tvOS app target to the project. I've already seen that it's easier to do another project (actually it's already working hehe). Almost no code would be shared by the projects, so for now they're going to be a different app. 
If merging with the iOS project works ok without too much fuss, I'll try it before releasing.

**Comment by MartinAyla** [comment]
Luis,

An option to remux without transcoding would be nice. Should make channel changing faster, and give it a more TV feel.

**Comment by nilzen** [comment]
Any updates on this @zipleen ?

**Comment by zipleen** [comment]
It's going to take a while... join https://gitter.im/zipleen/tvheadend-iphone-client for latest updates
