### ISSUE TITLE
Fix stuttering channel list

### ISSUE THREAD

**Issue by vicegold** [zipleen/tvheadend-iphone-client#167]
Scrolling on the channel list is extremely slow/juddery. I can only scroll in 20px steps, nothing animated at all.

If you turn on the Battery-saving mode of iOS9 you can't scroll at all anymore. It just doesn't react.

Tested on an iPhone 6.

**Comment by zipleen** [comment]
Btw, I don't have such a huge slowdown in an iPhone 5 - I guess it could be due to the channel pictures having a small resolution?

**Comment by zipleen** [comment]
Hi!

I've noticed this but I never found a decent fix. This will need to be postpone until the full rewrite to iOS 8! (It will take some time..)
