### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by doodster** [zipleen/tvheadend-iphone-client#168]
Hi,
Whenever I'm trying to open channels list I got the message:
Network Error
Expected status code in (200-299), got 1.
Other clients (vlc plugin on Windows, Tvhguide on Android) works fine.
I tried on Tvheadend server on raspbian and Synology, with the same effect.

Regards,
Chris

**Comment by zipleen** [comment]
Hi,

Try updating to the just released version and delete and add the server again

**Comment by doodster** [comment]
It's working, thanks!
