### ISSUE TITLE
Recording of TV series are sometimes to shor

### ISSUE THREAD

**Issue by muratb83** [zipleen/tvheadend-iphone-client#170]
Hello,

i'm recording series with the tvhclient and recognize that the record starts too late and terminate it to early.
You can solve this issue if you add an option to extend the start and the end of the records for some minutes. It's frustrating if its missing some seconds of the records. 

best regards

Murat

**Comment by zipleen** [comment]
Hi Murat
That's not a setting for tvhclient to handle - tvheadend already does that for you .
In tvheadend interface, go to settings, recording, select your default profile and input on the right the number of minutes you want a recording to start before and after (it's called extra padding before and after recording)
