### ISSUE TITLE
AFHTTPClient.h File Not Found

### ISSUE THREAD

**Issue by gtkow** [zipleen/tvheadend-iphone-client#172]
Hi, 

I try to compile the source but I have always the same problem... When he try to compile the tvheadend-ios-lib I have the error : AFHTTPClient.h File Not Found.

I have followed the instruction (git clone, pod install)...

Have you a solution?

Thank's for your help!!

**Comment by zipleen** [comment]
Yes, AFNetworking had the tree rewritten for some reason and the referenced commit does not exist anymore.

if you can, just go into tvheadend-ios-lib and git checkout tvOS branch and then init/fetch the submodules. That branch has a reference to my forked afnetworking repo.

Or you can substitute the tvheadend-ios-lib/vendor/AFNetworking with https://github.com/zipleen/AFNetworking/tree/1.x which is the correct version.
