### ISSUE TITLE
Wrong hour format in 12h

### ISSUE THREAD

**Issue by garanda21** [zipleen/tvheadend-iphone-client#173]
If you have in your phone configured the 12h the times in the app are showing wrong, see the image:
![Image of Yaktocat](http://i.imgur.com/5VecIER.png)

**Comment by zipleen** [comment]
Hi
I've noticed this in the tvOS version and it's fixed there.

I'll fix this in the next ( 2.7.9) version

**Comment by zipleen** [comment]
this should have already been fixed.
