### ISSUE TITLE
AFHTTPClient.h file not found

### ISSUE THREAD

**Issue by ssaguiar** [zipleen/tvheadend-iphone-client#174]
I have done everything as explained in main page of the project, but when I try to compile the application, I get:

/Users/ssaguiar/Downloads/tvheadend-iphone-client/tvheadend-ios-lib/tvheadend-ios-lib/TVHJsonClient.h:13:9: 'AFHTTPClient.h' file not found

The lib hs compiled without errors but the app gives the above one.

**Comment by zipleen** [comment]
please check https://github.com/zipleen/tvheadend-iphone-client/issues/172
it's probably the same thing
