### ISSUE TITLE
IP-adres format issue (iPhone vs IPad)

### ISSUE THREAD

**Issue by beninhos** [zipleen/tvheadend-iphone-client#177]
Hello,

I'am using the latest version of to headend client on both iPad retina and iPhone 6s. On the iPad I get the unsupported url error which I do not get on my iPhone.

Both addresses are put in 100% the same. Both go over my external wan. No vpn is used. 

What can cause this?

**Comment by zipleen** [comment]
There's no difference in code from the ipad and iphone, in regards to connections.

Make sure that the ip address you're connecting to is accessible through safari.

**Comment by beninhos** [comment]
The address is accessible via safari on the iPad. Error code is 999 in thvclient. Just reinstalled it to give it a clean go..

**Comment by beninhos** [comment]
Just cleared the log. Which showde à http - Get error -4 with a different (1 year old) ipadress than the one I just entered. After I cleared the log, the IP address got though. Now it works. 


Could it be, that the error log was conflicting with new settings?

**Comment by zipleen** [comment]
The log has nothing to do with the connection, it just shows the received log messages from tvheadend (server!)

Anyway, if it connects maybe something funny happened with the settings at some point..
