### ISSUE TITLE
No Audio on Apple TV 4

### ISSUE THREAD

**Issue by next2non** [zipleen/tvheadend-iphone-client#178]
There is no audio when played on Apple TV whereas it works fine on iPhone.

**Comment by zipleen** [comment]
Is this still happening? There's a new version coming out in a few days time that contains a new VLC build

**Comment by next2non** [comment]
It's working fine now. Thanks

**Comment by next2non** [comment]
Hi 

It's me again the same problem of audio again on Apple TV 4, but this time only IPTV channels. Channels from my satellite is working fine (both audio and video) but the iptv channels I get only video. Whereas on the iPhone I have both audio and video for the iptv channels

**Comment by zipleen** [comment]
mmmmm

by any chance those channels have AC3 encoding ? because if they do, I don't think AC3 is available in VLC, you'll need a decoder for that (like your tv probably already does). I'm not too sure about this, but double check if your channel works with the normal VLC app in tvOS !

**Comment by next2non** [comment]
Just checked on VLC and audio and video are there on the same channel I'm having issue with TVHClient

**Comment by zipleen** [comment]
just to be sure, did you test in VLC on the apple tv itself ? 

vlc in a desktop environment does not count!

also, tvhclient is using the latest VLCKit, which is somewhat similar to the latest vlc binary in the tv app store, so they should not differ in anything (I don't add anything to VLC code, there's no changes to the build of VLC at all)

**Comment by next2non** [comment]
Yeah did the rest on Apple TV 4 and no where else

Can you test this channel please?

http://rt.ashttp14.visionip.tv/live/rt-global-live-HD/playlist.m3u8

**Comment by zipleen** [comment]
I've asked on the gitter tvhclient channel, and ArtDoger was nice enough to test that stream, and it seems to work fine for him.

He's using tvheadend 4.1-2484 from 2017-03-20. Can you try upgrading to at least this version and re-testing ? 

check chat.tvhclient.com if you want to have more real time updates.

**Comment by next2non** [comment]
I updated the tvheadend server to 4.1-2493, but still no audio !!! The same channel if I run on kodi or TV headend Live Channel (Android) there is audio. So I cannot understand why only on TVHClient Apple TV there is no audio, on iPhone TVHclient it works fine and audio is there :(

**Comment by zipleen** [comment]
I've asked a friend of mine and he also has the stream audio working ok!

So we now have 2 users that have confirmed that specific stream working ok.

Do you want to start a new tvheadend server, with a blank configuration and configure that iptv stream? It might be something that you have configured in the server...

I have no idea what it could be..

**Comment by next2non** [comment]
I also don't know, I tried as you suggested and installed a new tvheadend server on another device and tried to stream that iptv channel only, but the same thing, the only place it fails to audio along with the video is Apple TV again :( I myself not sure what is the problem. I think one month back (comments up) this iptv channel was working fine, so I don't know what changed

**Comment by zipleen** [comment]
Ok both users were using the iOS version, using tvOS they confirm there's no sound for that stream.

**Comment by next2non** [comment]
So now it means I'm not isolated with the problem :) hope you could fix it, cause I have other iptv streams they also do not have audio.

**Comment by zipleen** [comment]
I've tried compiling the latest VLCKit version, but the iptv audio is still not there. I still need to try this with VLC..

**Comment by zipleen** [comment]
all tested in the simulator and not on the actual apple tv:

Latest TVVLCKit - no sound
TVVLCKit-unstable 3.0.0a24 - no sound
TVVLCKit-unstable 3.0.0a10 (this is the latest vlc master) - no sound
I haven't tested with vlc 1.0.7 which is the latest one from the app store.

**Comment by next2non** [comment]
I just tested the latest VLC 1.0.7 (tvOS) and the iptv stream for both audio and video works fine

**Comment by zipleen** [comment]
is this still an issue with the latest vlckit? 

If this is still happening, re-open the ticket after testing with the latest beta versions on test flight
