### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Stephan296** [zipleen/tvheadend-iphone-client#182]
Dutch translation for your great app.
I want to help you, if you want it.

**Comment by zipleen** [comment]
Send me an email with your email, so I can add you to transifex !

**Comment by Stephan296** [comment]
Hello,

My email is stephan296@hotmail.com

Regards,

Stephan


-------- Oorspronkelijk bericht --------
Van: Luis Fernandes <notifications@github.com>
Datum: 19-10-16 13:21 (GMT+01:00)
Aan: zipleen/tvheadend-iphone-client <tvheadend-iphone-client@noreply.github.com>
Cc: Stephan296 <stephan296@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [zipleen/tvheadend-iphone-client] Dutch translation (#182)


Send me an email with your email, so I can add you to transifex !

-

**Comment by zipleen** [comment]
I've deleted the comment to remove your email from it

I've also added you to transifex !
