### ISSUE TITLE
Feature Request: Setting preferred subtitle language

### ISSUE THREAD

**Issue by sasosecnjak** [zipleen/tvheadend-iphone-client#184]
Hi, 

first of all, I want to say, Great work! 👍 
I'm using TvhClient on Apple TV and I love it. It would be very useful to add some kind of a setting a preferred subtitle language to use across all channels, the same applies for preferred audio stream (already mentioned here: https://github.com/zipleen/tvheadend-iphone-client/issues/176).

Kodi for an example have an option to store this per channel or globally, but for a start, one or another would be great.

If you have any more questions, just shoot :)

Regards,
Saso

**Comment by zipleen** [comment]
Sounds reasonable, both #176 and #184
added to trello board

**Comment by sasosecnjak** [comment]
Any ETA on this?

**Comment by zipleen** [comment]
No promises, but I'm having a look at this actually

**Comment by zipleen** [comment]
new version in testflight has a new option to restore the selected audio and subtitle tracks

**Comment by sasosecnjak** [comment]
Is there any way to get into your testflight testing team, internal or external? 😊

**Comment by zipleen** [comment]
Send me an email with your email, or hop on to http://chat.tvhclient.com and send me your email over pvt

**Comment by zipleen** [comment]
1.2 now contains this feature
