### ISSUE TITLE
No Video Apple Tv 4

### ISSUE THREAD

**Issue by vehlajatt** [zipleen/tvheadend-iphone-client#186]
Getting audio 
But no video at all on all channels and purchased full version
And in my iphone internal player work but VLC have same issue no video at all

**Comment by zipleen** [comment]
The "full version" and the basic one do not use a different player. If it doesn't work on the basic version, the full version will not magically make it work.

I don't know what that could be, I'm releasing a new version soon with an updated VLCKit, that might fix the issues for you
