### ISSUE TITLE
Tvhclient not working fully with all channels after upgrade to Tvh 4.1-2403~gdf352fd-dirty

### ISSUE THREAD

**Issue by G-E-O-R-G-E** [zipleen/tvheadend-iphone-client#193]
Ater upgrade on Qnap NAS, tvhc does load only channel list, but no details on specific channels from same mux. For some other channels in different mux it works, for some channel the message is displayed: tvheadend returned malformed JSON, check your tvheadends character set on mux... checked, default values of encoding on all muxes, have not issue before the upgrade, then sudenly appeared.

**Comment by zipleen** [comment]
Hi

I've just upgraded tv headend to 4.1-2415~ge5f5a4278 and tvhclient seems to be working ok.

If you're seeing that message, you might have the wrong default character set. I'm releasing soon an update that will fix that character encoding problem (or better yet, not crash, but the characters will still be broken)
