### ISSUE TITLE
Feature Request: Add a Dark Theme to work with white channel Logos

### ISSUE THREAD

**Issue by SmoothMC** [zipleen/tvheadend-iphone-client#194]
Add a Dark Theme to work with white channel Logos

would be nice to have a Theme switcher from dark to light or something ;)

**Comment by zipleen** [comment]
next release will have the dark theme enabled, but I probably won't have time to mess around with the color scheme, which means it's going to be pretty awkward all those white channel blobs with a black background =)

**Comment by zipleen** [comment]
tvOS has a dark theme mode in the latest beta
