### ISSUE TITLE
Freezing Picture

### ISSUE THREAD

**Issue by IMEIICCID** [zipleen/tvheadend-iphone-client#196]
Hi , 

I have a issues on iPhone 5S, OS 10.3.1
TvhClient,  Version: 2.7.10
TVheadend,  4.1.2437

Problem I get a freezing picture, sound is ok.

I use DVB-T 2 HD TV

Can you help to solve it?

Best regards

**Comment by zipleen** [comment]
Hi, 

iphone 5s is probably too slow to playback HD streams in software mode. Is the stream HD ?

Also, vlckit for the iOS version is a very old version, which I might update in the near future, but I wouldn't have a lot of hope in making the iphone 5s work (vlc is software decoding only). You might try using another player which is able to do hardware decoding to see if it works, or try the latest vlc version and play to it.

**Comment by IMEIICCID** [comment]
Hi Zipleen,
thx for reply. I did try all the streaming profiles which TVheadend offers by default.

Same problem with VLC. 
The HD stream ist with freezing picture by using profile: pass and HTSP. 

The Matroska profile does not work at all. Maybe my NAS, where TVheadend ist running, ist not fast enought to transcode.

So than iphone and NAS are to slow.

Best regards

**Comment by zipleen** [comment]
pass does not transcode, so the nas shouldn't be a problem.

but the iPhone is the problem. if you said you tried with vlc and it does exactly the same thing, you then have your answer - tvhclient just bundles vlckit, it does not have any special thing in it.

Try using other players, like nPlayer or good player to see if it works in your iPhone! Other than that, I can't really do much more :(
