### ISSUE TITLE
Latest 4.2 Not Supported?

### ISSUE THREAD

**Issue by MartinGoodwell** [zipleen/tvheadend-iphone-client#198]
Error Message is
Server Not reachable or Not yet ready to connect 

Backend is reachable in the browser and from other clients though

Server API version 27

**Comment by zipleen** [comment]
Hi
It seems tvheadend 4.2 does work, although I haven't personally tested that, but some users say it does work.
Can it be permissions on the user? You can join chat.tvhclient.com to chat about this

**Comment by zipleen** [comment]
latest 3.0.0 beta seems to be running ok with 4.2 / 4.3

I also have no issues with the current stable one, if there's any specific issues please join chat.tvhclient.com so we can discuss them realtime
