### ISSUE TITLE
Channel thumbnail border

### ISSUE THREAD

**Issue by MarhyCZ** [zipleen/tvheadend-iphone-client#199]
Hi,
Would you consider either changing aspect ratio of the channel logo placeholder to square or even not show it at all, so all kinds of icons look good?

![img_0604](https://user-images.githubusercontent.com/6696872/29902967-952025e8-8e01-11e7-9d9f-446ae2107dfb.PNG)

**Comment by zipleen** [comment]
![img_7329](https://user-images.githubusercontent.com/1225055/29922887-603fab8e-8e4f-11e7-89fa-e4b3db6ebf61.PNG)

You mean, this option that exists in settings? =)

On the different ratios, I'm trying to find a way with the new release to support it, but probably will take time.

As an interesting note, here's the most commonly used ratios for the past 2 years
<img width="551" alt="screen shot 2017-08-31 at 13 24 32" src="https://user-images.githubusercontent.com/1225055/29923017-d9040704-8e4f-11e7-8f5e-ca0e6f41ba55.png">

tvhclient uses a stupid 1.2 ratio.. It would be nice if I could support some aspect ratios...
