### ISSUE TITLE
Do not support Chinese fonts

### ISSUE THREAD

**Issue by pcehh** [zipleen/tvheadend-iphone-client#201]
I update IOS 3.0.0(739).  All the sudden, it cannot support any Chinese tradition fonts at description but crazy font. It worked at last version. Please help.

**Comment by zipleen** [comment]
Hi!

Sorry, this is very bad and we need to fix it but I need your help.
Can you join chat.tvhclient.com so we can talk in real time so it’s easier?

**Comment by pcehh** [comment]
![c218b4b6-49ce-467e-ab1a-dd8b5db2c252](https://user-images.githubusercontent.com/32607284/31314998-b05c07a2-ac40-11e7-89d6-f8ba82d6ce6f.png)

**Comment by zipleen** [comment]
Hi!
I’ve changed the internals and that’s obviously the issue, but I need your help - I don’t have access to a server which contains Japanese characters. Can you provide a dump of your EPG or allow me temporary access to a server that has that EPG? 
It would be faster if you joined chat.tvhclient.com so we can talk in real time

**Comment by zipleen** [comment]
Hi, I still need help solving that issue. If you can't go to http://chat.tvhclient.com to chat, can you give me access to the server where that happens?

If you can't, I'll need a dump of one EPG call - I've explained that more or less here https://github.com/zipleen/tvheadend-iphone-client/issues/127#issuecomment-30250725 but that one is requesting /channels and I need EPG, so you'll need to request `/api/epg/events/grid`, save it directly to a file and send it to me.

**Comment by pcehh** [comment]
Sorry. I m at hongkong timezone and may opposite to you.  I can’t share this private server which is not belonging to me. This morning I check it again and it sudden return to normal from all my IOS devices. I m so happy now and sorry to trouble you. Appreciate your great work.

**Comment by pcehh** [comment]
![c1e157ae-f4d0-48e7-90a5-50ac8fdf5dfe](https://user-images.githubusercontent.com/32607284/31322720-ceb6a6dc-accf-11e7-8b5c-d1e4587aa109.jpeg)
