### ISSUE TITLE
List of Recordings get corrupted

### ISSUE THREAD

**Issue by jecdk** [zipleen/tvheadend-iphone-client#202]
List of "Recordings" gets corrupted after viewing the list of "AutoRec".
First everything looks normal, but after selecting "AutoRec" and going back to either "Completed" or "Upcoming", then either text, icon or both are missing from some items.
Going back again to "AutoRec" may even corrupt more items in all the lists including "AutoRec".
Pullling down the window to force an update of the list does not bring back an uncorrupted list.
Only a force close of the app and relaunching bring back the uncorrupted lists.

Have tried to restart the TVHeadend server, but that did not change anything
I think the problem started from version 3.0.0 or maybe 3.1.0.

Jens

**Comment by zipleen** [comment]
Thanks for the report
This has been fixed in version 3.2.1 which is waiting for review right now

**Comment by zipleen** [comment]
this should be fixed in 3.2.2
