### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by arressen** [zipleen/tvheadend-iphone-client#203]
The latest updates (Oct 15) have created a problem. In the recordings view, it is no longer possible to switch between upcoming/recorded/authored/etc. The bar appears to be there, but no buttons are visible. Really excited when I saw the new features added, but this is a significant problem. Tried re-starting app, and rebooting iPad, but no improvement.
Regards

**Comment by zipleen** [comment]
which version build do you have?

can you show me a screenshot of that bar disappearing ?

**Comment by arressen** [comment]
Hi Luis. Here is the information you asked for.
		
		


		
	_____________________________

**Comment by zipleen** [comment]
I think you missed the details =)

also, you might want to remove the reply because it contains your email...

**Comment by arressen** [comment]
Let's try this again... they were attached, but somehow got dropped.

![img_0285](https://user-images.githubusercontent.com/12573902/31589249-7824c674-b1f6-11e7-8ad7-33b3b135e5eb.PNG)
![img_0286](https://user-images.githubusercontent.com/12573902/31589250-7842fc48-b1f6-11e7-8ae0-71ad486cc7f1.PNG)

**Comment by arressen** [comment]
And iOS version is 10.3.3. As far as I'm aware it was working correctly before the update(s) today.

**Comment by zipleen** [comment]
thanks for letting me know, I only have an iPad Pro in iOS 11 and it seems this is broken on iOS 10 and iOS 9
I'll have a look and push out a release as soon as possible.

If you want to beta test the app let me know, send me your email and I'll add you to the beta testers (but don't reply to github, this is a public ticket)

**Comment by zipleen** [comment]
ok, fix will come up in version 3.2.2 ! 
Just need to wait for apple to approve the build

**Comment by arressen** [comment]
Great job for getting this turned around so quickly - thank you. I'm not clear where you were able to see my email address, but removed post just in case. Looks like it's not required in this instance, but happy to help with beta testing if required. Not clear how to send you private message.

**Comment by zipleen** [comment]
I’ve removed the email address.
Join chat.tvhclient.com and you’ll be able to chat in real-time with the other beta testers - you can send private messages there.
