### ISSUE TITLE
Search bar only half visible 

### ISSUE THREAD

**Issue by duffy6** [zipleen/tvheadend-iphone-client#204]
Seen in latest IOS10

**Comment by zipleen** [comment]
you mean in the "now" screen right?
Because there's search bars in channels, recordings, log and the now screen

Yes, I've noticed this yesterday and the next update 3.2.3 will fix that.

This only affects ios10 and ios9 people, upgrading to ios11 fixes this issue

**Comment by duffy6** [comment]
Yes, right in the "now" screen!

Thanks for fixing this!
