### ISSUE TITLE
Fullscreen on Lightning Digital AV Adapter

### ISSUE THREAD

**Issue by aleroot** [zipleen/tvheadend-iphone-client#212]
I'm using your ipad IOS app to watch TV, and I've connected the iPAD with the TV through an HDMI cable and the Lightning Digital AV Adapter, but the video doesn't go full screen but it remains with two black bands on the sides like on the IOS springboard ...

Netflix and VLC apps are putting the video correctly in fullscreen when playing.

see this forum for more information : https://apple.stackexchange.com/questions/288521/how-can-i-display-ipad-content-fullscreen-with-hdmi-on-a-tv

See apple documentation for more information : https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/WindowAndScreenGuide/UsingExternalDisplay/UsingExternalDisplay.html

I hope to see an update containing the fix

**Comment by zipleen** [comment]
This is odd, I've used this before but I have to say that I haven't tested using the latest version 3.x.x after I upgraded vlckit.
It should be exactly the same as VLC, and if it was working before it should still work.

I'll test this out to see if I can reproduce the issue

**Comment by zipleen** [comment]
Ok fixed this in the beta version.
Next version in the App Store should have this.

Just waiting for VLC to release the new version that doesn't reboot the iPhone on 4K HEVC streams :)

**Comment by zipleen** [comment]
Also, HD channels seemed to be ok in the stable version, but SD channels seemed to have the black border

**Comment by zipleen** [comment]
I'm still waiting for the https://code.videolan.org/videolan/VLCKit/issues/123 bug to be fixed (if it can ever be fixed), otherwise tvhclient might start crashing all iPhone X with HEVC content and that's bad =)

Once it's fixed I can finally push the new build with this fix.

**Comment by zipleen** [comment]
Version 3.2.6 is now in review with this fixed!
