### ISSUE TITLE
No Dolby 5.1 output Apple TV 4k

### ISSUE THREAD

**Issue by jteeuw** [zipleen/tvheadend-iphone-client#214]
When i stream a tv channel i do not get dolby 5.1 only 2.0, on my Kodi setup i do get 5.1 audio. 
The problem is with all channels

**Comment by zipleen** [comment]
is this still an issue? 

as far as I know, passthrough has always been working. I can't really do much more because it's all internal vlc code. If you want, try with VLC and see if SPDIF works correctly there - if it does then open a ticket detailing the steps to reproduce!
