### ISSUE TITLE
Title of media playing

### ISSUE THREAD

**Issue by bhaap** [zipleen/tvheadend-iphone-client#217]
Hi

When using "home sharing" in to show what my apple tv is currently playing when playing from the tvOS app i get a random number as the media_title. Any way to make this show the current channel instead?

**Comment by zipleen** [comment]
hi

well yeah this is normal, I would assume this wouldn't even be used lol 
but yeah, I actually fixed this in the beta versions of tvOS, but I haven't been able (for the past 6 months) to find a stable vlc version for tvOS. 

It seems it's now getting stable, so an update with all these little fixes should come soon

**Comment by zipleen** [comment]
I think this now has code to show the name of the channel. Not terribly certain though, re-open if this pops up again on the latest versions
