### ISSUE TITLE
Cannot play recordings on Apple TV

### ISSUE THREAD

**Issue by kianrafiee** [zipleen/tvheadend-iphone-client#219]
When I hit Play for a recording in tvhclient on Apple TV, it shows a black screen for a split second and then comes back to the recording information. It doesn't play the stream.

This is the tvheadend status log:

`2018-01-30 18:54:08.627 http: 192.168.1.22: HTTP/1.0 GET /dvrfile/6f60f4874224a76ecc9f06d15c21eae3 -- 500`

When I open up the recording through MrMC app on Apple TV, which has a TVHeadEnd module/add-on, I can play it fine.

The video file is also titled "Show Name - SXXEXX.mkv" so I am not sure if maybe its not getting the correct file name?

**Comment by zipleen** [comment]
Hi

I'm not sure why this happened, recordings seem to be ok. You might have a weird setting in your tvheadend config that I might not know about. Can you create a user for me and give me access so I can debug this ? 

Also, there's been a lot of fixes in the client side, but I still haven't been able to have a stable beta version of the app. If you want you can try the latest beta to see if it fixes this issue - join chat.tvhclient.com and send me your email over pvt

**Comment by kianrafiee** [comment]
I will set this up tomorrow or by the weekend at the latest. Thanks. Ill also shoot you my email for the beta. Itll start with kian@ :)

**Comment by zipleen** [comment]
any updates? the new version has been released and all

**Comment by zipleen** [comment]
if this is not fixed, we can re-open this again and add more detail.

**Comment by kianrafiee** [comment]
Sorry about that. I got rid of my apple tv and got a Shield. I was meaning to update you on that.

**Comment by Marty56** [comment]
play back of recordings is also not working on iPhone.
Any tips how to configure Tvheadend to make this work?
Kodi is working fine but has lousy UI on iPhone.

**Comment by zipleen** [comment]
Recordings are working for me, so it must be some config from the server. Can I access the server to test it myself? Maybe it's a bug that I have to fix
