### ISSUE TITLE
tvOS: default action an faster EPG accessing

### ISSUE THREAD

**Issue by kalle2000** [zipleen/tvheadend-iphone-client#221]
Once an entry from EPG is chosen and confirmed by enter, a new pop-up appears askign whether to play or record. Is still possible to have a default action in the settings, e.g. enter is defaulting to play?

Once the channel is playing, is there an easy way to directly call the EPG, like ENTER or another key?

**Comment by zipleen** [comment]
I was thinking about this, and this case only matter for the "currently playing" show. What I could do is enable automatically "play" if you chose a currently running show, but for everything else you get the popup.

Unfortunately, the EPG is not available while playing back a channel - but you can swipe up to switch channels!

**Comment by kalle2000** [comment]
Fine with me, as i normally do not schedule recordings via the tvOS app.

[quote]Unfortunately, the EPG is not available while playing back a channel - but you can swipe up to switch channels![/quote] technically not available or functionality is not planned to be implemented?

Is it possible to support "spcial keys" (for the ones among us not using original apple tv remote), like
R - recording
E - EPG
P - play

thx & rgds
kalle

**Comment by zipleen** [comment]
I don't think so, I haven't seen any special keys available to developers. 

I suspect that the apple tv just ignores those key presses completely.

**Comment by zipleen** [comment]
So, I forgot that you actually can just hit "play" in any of the cells and the channel will play (instead of selecting the cell).

Anyway, I've now changed the new version to also playback the currently running the epg channel
