### ISSUE TITLE
Feature Request: Showing „errors“ and „data errors“ in Recordings

### ISSUE THREAD

**Issue by HighCoder98** [zipleen/tvheadend-iphone-client#222]
First of all I love your app.
But is it possible to show „errors“ and „data errors“ in the recordings view?
This would be very convenient for me.
Thanks.

**Comment by zipleen** [comment]
hi! thanks!

first of all, which version of the app? iOS or tvOS ?

where exactly are you talking about showing errors? in the list view I have no space, in the iOS version of the detailed view I have space but I need to know what is "errors" and "data errors" fields =)

**Comment by HighCoder98** [comment]
Hello.
 
I am using the iOS App
 
I would like it to have in the detail view when you click on a recording.
 
If I run a HTTP POST request on http://<ip-of-server>:9981/api/dvr/entry/grid_finished to get all finished recordings, then I’m getting a json response, with a list of all finished recordings and there are keys called „errors“ and „data_errors“.
„data_errors“ occur when there is a bad signal for example when there is bad weather outside.
I don’t know the exact meaning of the „error“ field, but I can tell you that tomorrow.
 
I know that the POST request is against the HTTP API which the extJS Frontend is using. I don’t know if you’re using the HTSP protocol but I assume that the field is called „data_errors“ too.
 
The fields „errors“ and „data_errors“ are existing on every DVREntry JSON Object response against the HTTP API, so it could be displayed on all recordings, even on a upcoming recording.
 
It would be very nice i fit would be included in the next build.
 
If you need further information, please tell me.
 
Thanks.

**Comment by zipleen** [comment]
nice.

tvhclient only uses HTTP for everything.

if you can provide me with an example JSON of those fields, I can include that right away

**Comment by HighCoder98** [comment]
{
"entries": [
{
"uuid": "e0c2c924136331c6690cfba9b0598fae",
"enabled": true,
"start": 1518651244,
"start_extra": 0,
"start_real": 1518650794,
"stop": 1518657258,
"stop_extra": 0,
"stop_real": 1518657678,
"duration": 6854,
"channel": "f8eb0877ac6091e03c06b474ec013b12",
"channel_icon": "",
"channelname": "ProSieben",
"title": {
"ger": "Disturbia"
},
"disp_title": "Disturbia",
"subtitle": {
"ger": "Thriller, USA 2007"
},
"disp_subtitle": "Thriller, USA 2007",
"description": {
"ger": "trimmed :D"
},
"disp_description": "trimmed :D",
"pri": 2,
"retention": 0,
"removal": 0,
"playposition": 0,
"playcount": 0,
"config_name": "b1605c8bd3fb441e5e21cbea2d12ac38",
"creator": "trimmed",
"filename": "trimmed",
"errorcode": 0,
"errors": 0,
"data_errors": 0,
"dvb_eid": 0,
"noresched": true,
"norerecord": false,
"fileremoved": 0,
"autorec": "",
"autorec_caption": "",
"timerec": "",
"timerec_caption": "",
"parent": "",
"child": "",
"content_type": 0,
"broadcast": 0,
"url": "trimmed :D",
"filesize": 3582942540,
"status": "Completed OK",
"sched_status": "completed",
"duplicate": 0
}
],
"total": 1
}

**Comment by zipleen** [comment]
ok I've added "errors" and "data_errors" to be shown in the details of the recording, once click to go into the recording

**Comment by HighCoder98** [comment]
Thank you so much!

**Comment by zipleen** [comment]
Did it pop up the errors ?
