### ISSUE TITLE
Issues for tvhClient ATV version 1.1.0

### ISSUE THREAD

**Issue by jecdk** [zipleen/tvheadend-iphone-client#223]
Issues after update to tvhClient for ATV version 1.1.0(186):
1) After pausing playback of a recording, one cannot start playback again (toggling "play/Pause")
2) Playback has become choppy. Seems that when turning "Hardware Decoding" Off, playback again is more even.

Issues are the same for "pass" and "matroska" recordings. 

ATV 4K (tvOS 11.2.5)

**Comment by zipleen** [comment]
Hi!

Well the first problem is embarrassing, although I haven't done a lot of "pause/play", I was playing more with the seeking, which is how you get around this, just seek a little bit back and it will continue playback. The bug has been fixed though.

On the second one, playback being choppy could be one of the side effects of the new VLC, although there's not much I can do about it (it's already the latest version). Hardware decoding option is there for that reason, as some streams don't like hardware decoding that much. On my home servers and also beta testers seem to be happy with the results, unfortunately there's no way for me to test every single possible combination of streams.
If you want, you can join chat.tvhclient.com and chat about that, maybe a little bit more details on the stream (or share a sample recording) could help debugging this issue!

**Comment by jecdk** [comment]
Hi,
Good to know that the pause/play issue will be fixed in the next version.
I do hope for the new release coming soon. For various reasons I record in "pass" mode, so using seeking for pause/play is far from easy.

I have investigated further regarding the choppy playback, finding that it depends upon which channel is recorded. I record via HDHomeRun from a cable provider (YouSee, Denmark - also providing channels from Norway and Sweden). I tried a few Danish channels that do not seem to have the problem, but swedish and norwegian channels do show the problem.
Below is a link to a recorded TS-file (zipped) form NKR1. When I play with "Hardware decoding" OFF, it played fluent, but setting  "Hardware decoding" ON, it plays really uneven.
[NKR1 Test file, to download from Google Drive](https://drive.google.com/file/d/11kE5JTBJbviMBCBsY0eD2Mw6mUqfy4vX/view?usp=sharing).

**Comment by zipleen** [comment]
Send me your email over email or chat.tvhclient.com and I'll add you to the beta testers - the play/pause is fixed there

**Comment by zipleen** [comment]
ok, confirmed that vlc for apple tv also does the same thing, so it's a vlckit issue.

**Comment by jecdk** [comment]
Have installed new beta version, and the "pause/play" is now working.
Choppy playback of recordings happens only for some channels and only with "Hardware Decoding" set ON (VLC issue).
