### ISSUE TITLE
ATV version recording sort order

### ISSUE THREAD

**Issue by jecdk** [zipleen/tvheadend-iphone-client#224]
I find the fixed sorting order in the iOS version very logical and user-friendly:
Upcoming recordings shows next recording at the top (ascending)
Completed recordings shows latest recording at the top (descending)
Thus different sort order for the two list.

In the ATV version, sorting order can be changed, but it will be the same for upcoming and completed recordings which I find much less logical and user-friendly.
Would you consider to make it fixed as in the iOS version, or make it possible to select different (persistent) sort orders for the two list?

**Comment by zipleen** [comment]
you know what, it's done. next build will have this feature included.

I've attempted to do this but I must have gotten lazy. The sorting is now independent from each screen and it's saved into settings, so choose whichever you want =)

**Comment by jecdk** [comment]
Oh thanks, that’s great.

**Comment by jecdk** [comment]
Got the new beta version 1.1.1 (194), and the independent sorting order now works as you described.
But now just a detail:
If you, while having the "cursor" down in the list, swipe left/right to change between upcoming/completed, the selected sort order do take effect correctly, but the label at the top displaying the type of sort order does not change to reflect the current sort order of the list.

**Comment by zipleen** [comment]
good catch. fixed on the next beta build!

**Comment by zipleen** [comment]
@jecdk by any chance have you tested the "automatic" deinterlacer? does it work?

**Comment by jecdk** [comment]
Sorry, have never tuched that issue, so no idea of how I can test this. Could you give a hint.

**Comment by zipleen** [comment]
you can have a look at https://github.com/zipleen/tvheadend-iphone-client/issues/209 for some examples of deinterlacing in action.

meanwhile I've noticed that auto deinterlacer selects the "x" deinterlacer which is not very effective on iOS. Thus I need to find a way to activate another deinterlacer, unfortunately this clashes with a vlc bug which crashes everything. 

I'm going to push a new version to the app store right now, with the TS seek fix but without the auto deinterlacer
