### ISSUE TITLE
TvOS version: recordings bombarding tvh

### ISSUE THREAD

**Issue by tonyschuite** [zipleen/tvheadend-iphone-client#227]
Hi there, 

love the app. Running it off my new ATV 4K, works really well.

I have an issue with playback of recordings:
tvheadend is version 4.0.8 (can't update because of freenas version)
recordings are made in MKV profile.
app version is release from app store

when starting a recording, it takes a while to load and then just shows the first frame and playback freezes. on the server side I see that it is actually making hundreds of connections to the server (forcing the connections to close does not work). Thus trashing my server.
It can only be recovered by closing the connection (restarting either ATV or tvh server, not by killing the app).

**Comment by zipleen** [comment]
hi!
sorry for the late reply, I'm really interested in this.
The opening a lot of connections could be because of the http-reconnect option that was added.

As I can't reproduce this, is there a way for you to give me access to your server so I can try to reproduce that problem locally ?

**Comment by tonyschuite** [comment]
sadly, no. I could try the alpha, see if that one has the same problem.
I was thinking maybe to upgrade to 4.2.5 but that would require updating freenas as well...

by reproducing locally, do you mean on the freenas server by SSH?
you could give me some pointers and let me try...

my provider does not allow remote access... sucks...

**Comment by zipleen** [comment]
any updates on this? 

Without me accessing the server it's going to be very difficult to debug what might be happening with the app.

Because I can't reproduce this error on my system, I can't help diagnose what's happening on your system. 

Isn't there a way to connect to the server somehow? Like connecting through a VPN

**Comment by tonyschuite** [comment]
yeah, I get that. would SSH work? I will look in to forwarding the port on my router. How will I contact you privately? not about to put IP and login on GH :P

**Comment by zipleen** [comment]
Join http://chat.tvhclient.com and you can talk via pvt 

Or if you want it's tvhclient@gmail.com

Do note that I can't do anything today because I'm out, but I can do tomorrow!

**Comment by tonyschuite** [comment]
status update: added a new jail (needed a cleanup anyway). I can now play the recordings, but no live channels.
I have a connection of tvhClient that I cannot disconnect and in the subsriptions tab that same connection is showing file://error

TVH version 4.2.5 (A19)
TVHClient version: TvOS 1.1.2 (208)

**Comment by zipleen** [comment]
That's very strange. Can I get access to the server?

**Comment by tonyschuite** [comment]
do you need SSH access or web access?

**Comment by tonyschuite** [comment]
just to give you an update:

so not being able to watch channels in 4.2.5 is definitely a tvheadend problem for me. I was able to do htsp connections with kodi fine. so i deleted that jail for now. 

back to the 4.0.8 version because live channels are more important to me. 

now recordings do work fine. apparently in VLC (not the iphone client) http streaming of recordings kinda sucks. it is not working at all...
i can play the actual files fine.

**Comment by tonyschuite** [comment]
It appears there is a new version of TVH on FreeBSD / Freenas / Freshports.
So this problem is resolved / an internal TVH problem.

closed
