### ISSUE TITLE
Full text search for a show in tv does not work.

### ISSUE THREAD

**Issue by cannonballgray** [zipleen/tvheadend-iphone-client#229]
Hi,

currently it is not possible to search/find an upcoming show in the future on tv channels.
Using iphone 6s (ios 11.3) with latest tvheadend client on ios.

Example:
1) tap on "now" and search for "alien" or "Alien" ( running on Kabel1, the 12th of April 2018 )
2) My client will not find this one. Does not matter if case sensitive or not.

-> I am sure to have a EPG
-> I am sure to parse all channels available
-> If I manually select Kabel1 and navigate to the 12th of April 2018 I can see the movie running at 22PM that day.

**Comment by zipleen** [comment]
Hi!

Can you do a little text? Open tvheadend web interface and do the exact same search to see if it finds the entry.
Then click on "full text" in the webUI and do the search again and see if it finds the entry.

Report back your results :)

**Comment by cannonballgray** [comment]
Hi,

I already tested that.
It also fails if I search on tvheadend via both, full text and/or just by the word.



Mit freundlichen Grüßen

Andreas Brandts
Wasmannstr 25
22307 Hamburg
Fon 040 18 08 66 07
Mobil 0176 24 28 06 65

**Comment by zipleen** [comment]
that's the issue. tvhclient does not search anything, it just asks tvheadend to search. If tvheadend returns a wrong result, tvheadend needs to be fixed - but there's nothing I can do in tvhclient =)
