### ISSUE TITLE
App not working after update

### ISSUE THREAD

**Issue by deeeblack** [zipleen/tvheadend-iphone-client#239]
Hi, after updating the iOS app recently, the TVHClient app is showing the incorrect info and will not load a stream. Everything has been working flawlessly for over 3-4 months. See picture for reference.
Unsure where the app is getting that IP under hostname.....any ideas?

TV headend build: Tvheadend 4.2.6-16
tvhclient: 3.3.2 (867)

![tvhclient_1](https://user-images.githubusercontent.com/18100269/48875699-6c276a80-ee35-11e8-87ab-17312037b384.PNG)

![tvhclient_2](https://user-images.githubusercontent.com/18100269/48875750-d04a2e80-ee35-11e8-84e1-a58b5c57bbcf.PNG)

**Comment by zipleen** [comment]
Hi

That has nothing to do with tvhclient, it's your server that's saying "no adapters available". Also the name-not-Set comes from tvheadend

You must have updated tvheadend server and didn't properly finished configuring it. 

Also tvheadend 4.2.6 is fully supported, I'm using that version daily (as well as a lot of other people)
