### ISSUE TITLE
Scrubbing does not work properly

### ISSUE THREAD

**Issue by rtahiry** [zipleen/tvheadend-iphone-client#242]
Hello,

Firstly, thanks for this great app. I usually use it to watch programs recorded by my tvheadend server. But when I watch a recorded program and use the top slider to move towards the middle, then the slider simply goes back to where it is currently playing. Thus I have to rewatch the record from the beginning :(. This occurs both on iPhone and iPad.

Note that scrubbing works properly on other desktop clients such as Kodi.

Thanks.

iOS 12.1.4
Tvheadend 4.3-1672~g0db0890a4 (A19)

**Comment by zipleen** [comment]
Hi,

That's a known issue for a year now :( you can track it here https://code.videolan.org/videolan/VLCKit/issues/157

**Comment by rtahiry** [comment]
Of course it's a VLC core issue rather than tvhclient problem. I guess this can be closed.

**Comment by zipleen** [comment]
should be fixed in 3.4.0
