### ISSUE TITLE
tvOS feature request: alternative quick channel switcher design

### ISSUE THREAD

**Issue by jlsalmon** [zipleen/tvheadend-iphone-client#248]
Thanks a lot for this app, it's great! I'm wondering whether you would consider accepting a patch to support an alternative layout for the quick channel switcher? I'm talking about the swipe up list of channels when watching a channel.

I would really like to have the channel list appear horizontally along the bottom of the screen, and scroll through it horizontally. It feels uncomfortable to me to swipe up to bring up the list and then swipe up again to start scrolling. It also feels odd to have to swipe to the right to hide the switcher. I think that a horizontal list along the bottom would solve both of those things. Swipe up to show, swipe left/right to browse, swipe down to hide.

What do you think? I'm very happy to work on something like this if you like the idea.

**Comment by zipleen** [comment]
That's a cool idea, want to join chat.tvhclient.com so we can talk? Probably I won't be able to reply right now but I'll reply tomorrow
