### ISSUE TITLE
Version 3.4.2 (887): date not selectable, missing bottom menu element

### ISSUE THREAD

**Issue by RannerDesign** [zipleen/tvheadend-iphone-client#256]
I just saw, that the screen layout on iPad (IOS 12.4.4) has changed in the last days (assume automated update, now 3.4.2, 887). Unfortunately the new layout is not very helpful, the old one (still active on an iPhone with IOS 13.3 and TvhClient 3.4.1, 885) is really much more better. So 4.3.2 looks like a degradation.

With 3.4.2 in the bottom menu there are only 4 elements (channels, recordings, EPG, status) while in 3.4.1 there are 5 (channels, recordings, now, status, log). the 3.4.2 "channels" looks similar to 3.4.1 "now" but a functionality like the 3.4.1 "channels" is missing.

With 3.4.2 "channels" channel and day are offered to be selected. Selection of channel works but selection of date hangs and does not show anything.

**Comment by zipleen** [comment]
Hey
Can you show me screenshots of what you mean? 

The only change I've done to the new version was fix the wrongly interpreted bandwidth values.
It was indeed compiled with the latest Xcode 13, which might have affected something.

**Comment by RannerDesign** [comment]
Hello,
thanks for your fast response.
Unfortunately, I didn't take screenshots immediately. So I tried it now 150 minutes later. And surprise, the screen layout had changed again and now was similar like before. I have no idea why (perhaps usage of the App while update in background running ???)
So my fear, that 3.4.2 looks like a functional degradation, is obsolete. Everything is fine so far.
Except one small thing on the iPad: when I touch on "Kanal" a channel list comes up for selection, when I touch "Tag" a date selection should be expected but the channel list come up. Screenshots attached.

[200127  tvheadend-iphone-client 3.4.2 iPad (IOS 12.4.4).pdf](https://github.com/zipleen/tvheadend-iphone-client/files/4119478/200127.tvheadend-iphone-client.3.4.2.iPad.IOS.12.4.4.pdf)
[200127 tvheadend-iphone-client 3.4.1 on iPhone (IOS 13.3).pdf](https://github.com/zipleen/tvheadend-iphone-client/files/4119480/200127.tvheadend-iphone-client.3.4.1.on.iPhone.IOS.13.3.pdf)

For me this is minor, so I'll close the issue. Sorry for that.

**Comment by zipleen** [comment]
Hi
That's the correct usage. Channel shows the list of channels so you can filter the search within that channel only. Tag shows you the list of your tags to search within a specific tag.

Say you have a tag "sports" and have all sport channels inside and want to search inside all those channels: you hit tag, sect sports and search.

Nowhere there's an option to search within a date...

**Comment by RannerDesign** [comment]
Hello,
thanks for the explanation. I use German as language. As channel was translated to "Kanal", I assumed that "Tag" was the translation of date. So everything is fine.
Thanks again for your help.

**Comment by zipleen** [comment]
I didn't do the German translation as I don't know German. What would be a good word for that Tag then? Kategorie ? Gruppe ? Etikett ?

**Comment by RannerDesign** [comment]
Tags in TVheadend look like groups of broadcasting organisations, so I would translate it as "Sendergruppe" or "Gruppe", if you need it short.
