### ISSUE TITLE
can program DVR, no stream possible (403 Error)

### ISSUE THREAD

**Issue by Jacuzzi73** [zipleen/tvheadend-iphone-client#260]
Hello,

with the TvHClient I can program the DVR , check what was recorded and see the epg data.
But when I want to stream a live channel or a recorded film (pass / MPEG-TS Pass-thru) I get the following error:

2020-03-21 08:11:49.648 http: 193.168.0.105: HTTP/1.0 GET (1) / stream/channel -- 403
2020-03-21 08:11:49.590 http: 193.168.0.105: HTTP/1.1 GET (1) / stream/channel -- 403

I am unexpierence and tried different things, but I was not able to fix it. 

Thanks for the support.
Jacuzzi73

Synology DS116 with DSM 6.2.2-24922 Update 4
HTS Tvheadend 4.3~221c29b

TvhClient Version 3.4.2 (887)
VLC for iOS 3.2.6 (344)
iphone 7 with iOS 13.3.1

**Comment by zipleen** [comment]
403?

I have a quick question, does your password contain # character or any other weirder characters? Can you attempt to use a more basic password and let me know if it works and which character broke it? 

If I remember correctly, there's a problem encoding passwords for VLC urls - the url encoding fails on some characters..

**Comment by Jacuzzi73** [comment]
Thank you for the hint!
It works fine now!

Jacuzzi73

**Comment by zipleen** [comment]
What "weird" character did you have in your password? Just so I can add it to the issue, I might add a popup message letting people know that if they have those characters it might have issues
