### ISSUE TITLE
Audio sync problems on tvOS 13.4

### ISSUE THREAD

**Issue by mielleman** [zipleen/tvheadend-iphone-client#262]
I have large audio sync issues with any tv stream in the tvhclient app on tvOS on my Apple TV 4K.

I suspect it is due to the app and not due to my setup because
- all other videos from all others tvOS apps (e.g. Youtube, Netflix) have no sync problems
- when watching the same tvheadend stream in VLC from a desktop there are no sync problems

I already tried
- choosing different audio stream (AC3 / PCM): no effect
- disabling hardware decoding: no effect
- disabling de-interlacing: no effect
- setting a audio delay: making it worse
- setting a audio speedup: making it worse
-- The stream starts out of sync but then gradually it gets worse and worse

my versions:
- tvOS 13.4 (latest)
- tvhclient 1.3.0 (248)

I am happy to test, try, install, beta or do anything.

**Comment by zipleen** [comment]
try 3 things:
- do a recording of a stream, play it back - does it happen as well ?
- upload me the stream, so I can experience this on my apple tv
- install VLC for apple tv, try the recording with VLC for apple tv. you might find that it will do exactly the same behaviour, and if so this means it's something to do with vlc specifically and we might have to go ask for vlc to fix whatever is weird with your stream

if you're lucky, it might be something weird on the stream that tvheadend might be able to remux on the fly. if you're extremely lucky it might be something like you not choosing the "pass" profile or some other setting in tvheadend.

**Comment by mielleman** [comment]
Hi @zipleen thanks for quickly responding.

1. _do a recording of a stream, play it back - does it happen as well ?_
Yup, no problem to reproduce.

2. _upload me the stream, so I can experience this on my apple tv_
[Link to recording](https://we.tl/t-4YW9ll8yGD) (will be deleted in 1 week)

3. _install VLC for apple tv, try the recording with VLC for apple tv_
Same thing happens after uploading it to VLC on my Apple TV
My VLC version 3.0.8 (308) based on 3.0.9

4. _it might be something like you not choosing the "pass" profile_
Nope, this is all pass. also the recording is pass

**Comment by mielleman** [comment]
Also made a post to the VLC forums for the iOS/tvOS software
https://forum.videolan.org/viewtopic.php?f=36&t=153154

**Comment by mielleman** [comment]
Ok, found some other Apple TV 4K users with the same setup. Who are also using tvhclient. They were not having issues. **I then restored my Apple TV 4K to factory settings using the menu option "Settings -> System -> Reset -> Reset and Update"**. After a lengthy reinstall and going through the reconfiguring of a fresh system, **the problem is gone**.
