### ISSUE TITLE
tvOS no sound over AirPlay

### ISSUE THREAD

**Issue by NotClear** [zipleen/tvheadend-iphone-client#263]
If I use airplay as sound output I get no sound. via hdmi everything works and also in other apps the sound playback via airplay works. I have the same problem with the "Twitch" app for the AppleTV, so I think it is a problem of the app.
![homepod-am-apple-tv](https://user-images.githubusercontent.com/47524198/92368152-a25fd800-f0f7-11ea-9a6f-4684b4440f80.jpg)

**Comment by zipleen** [comment]
It doesn't work? Oops
I don't have an HomePod to test with, and none of the testers complained so I didn't even remember about that.
I'll have a look in a few weeks

**Comment by NotClear** [comment]
> It doesn't work? Oops
> I don't have an HomePod to test with, and none of the testers complained so I didn't even remember about that.
> I'll have a look in a few weeks

i use two Sonos speakers but the AirPlay function would be the same as with a Homepod and with Netflix, Amazon Prime or Youtube i don't have that problem.

**Comment by NotClear** [comment]
the problem was that at the beginning of the stream it took about 30 seconds to 1 minute to get sound. now the sound can't be delayed no matter if I set the delay to maximum or minimum the sound hangs behind

**Comment by zipleen** [comment]
So the sound delay feature is somewhat broken in vlc then. 
I won't be able to do anything for the nest 2 weeks though, but I need to get around fixing one or two bugs that were reported then

**Comment by zipleen** [comment]
I've identified a problem with this, as now I have an homepod mini to test this with. 

I'll be looking into this in the coming weeks
