### ISSUE TITLE
tvOS 14.2 stuck on  Player Gestures Screen

### ISSUE THREAD

**Issue by Fritzberger** [zipleen/tvheadend-iphone-client#266]
Hello,

Just bought the App in the AppStore and 
Can‘t Proceed from the Player Gesture Tutorial Screen on a Apple TV4K with TvOS 14.2.  Closing the App , restarting the Apple, reinstalling the App , nothing helps , always stuck at the „Tutorial Screen“.

**Comment by zipleen** [comment]
Hi

Yes it seems 14.2 introduced this bug.

Unfortunately there's no quick fix! The app is still being converted to tvOS 13/14 sdk.

Join discord to get the beta link when I push a beta build for tvOS (the link might only work once there's a beta, I'll warn in discord when that's so)

**Comment by zipleen** [comment]
New version on the app store fixed this!
