### ISSUE TITLE
Unable to use it on Apple TV HD and tvos15

### ISSUE THREAD

**Issue by asuatton** [zipleen/tvheadend-iphone-client#275]
Your app is not optimized for TVOS 15 and in Apple TV HD it’s just unusable.   Tons of video lag, unsynchro video/sound, freezed pictures etc…..  
we payed this app it can be cool to update it (tvos15 are in public since a month !!)

**Comment by RaresAil** [comment]
looks like this app is dead

**Comment by zipleen** [comment]
tvOS 15? I'm running the app on TvOS 15 for about a year. If you mean TvOS 16, then I haven't tested that.
What specifically happens on tvOS16 that doesn't happen on 15? 
i will test this on 16, as soon as it gets released (as I only have 1 Apple TV in my house, and I don't want to install beta software on it).

**Comment by zipleen** [comment]
You'll need to give a better report on what's not working on tvOS 15, re-open the issue or go to the discord and chat real time there to figure out what's wrong.
Usually the lag and desync is about VLC / tvheadend stream, and there's very little I can do about that (I don't control tvheadend features, the server or the quality of the stream). 

tvOS app does need to have VLCKit upgraded and the only (very annoying) issue that it has is the homepod airplay feature, which doesn't work reliably.
